#!/bin/bash

primes=(2 5 7)

for p in "${primes[@]}"; do
	rm -rf "./${p}"
	mkdir "./${p}"
done

#setenv MAGMA_USER_SPEC "/home/cp/Git/etale-algebras/spec"
magma /home/cp/Git/etale-algebras/EtaleAlgebras/run_etale.m
