#!/bin/bash

MODULI="-moduli 16,16,16,16,16,16,16,16"
VARMODULI1="-varmoduli 16,16,16,16,16,16,16,16"
INPUT1="-input input/2/e0/{x+1x+1x^3+x+1x^3+x+1}/1.txt,input/2/e0/{x+1x+1x^3+x+1x^3+x+1}/2.txt,input/2/e0/{x+1x+1x^3+x+1x^3+x+1}/3.txt,input/2/e0/{x+1x+1x^3+x+1x^3+x+1}/4.txt,input/2/e0/{x+1x+1x^3+x+1x^3+x+1}/5.txt,input/2/e0/{x+1x+1x^3+x+1x^3+x+1}/6.txt,input/2/e0/{x+1x+1x^3+x+1x^3+x+1}/7.txt,input/2/e0/{x+1x+1x^3+x+1x^3+x+1}/8.txt"
VARMODULI2="-varmoduli 16,16,16,16,16,16,16,16"
INPUT2="-input input/2/e0/{x^2+x+1x^6+x^4+x^3+x+1}/1.txt,input/2/e0/{x^2+x+1x^6+x^4+x^3+x+1}/2.txt,input/2/e0/{x^2+x+1x^6+x^4+x^3+x+1}/3.txt,input/2/e0/{x^2+x+1x^6+x^4+x^3+x+1}/4.txt,input/2/e0/{x^2+x+1x^6+x^4+x^3+x+1}/5.txt,input/2/e0/{x^2+x+1x^6+x^4+x^3+x+1}/6.txt,input/2/e0/{x^2+x+1x^6+x^4+x^3+x+1}/7.txt,input/2/e0/{x^2+x+1x^6+x^4+x^3+x+1}/8.txt"
OUTPUT="-output output2e0mod16.txt"
./build/apps/program $MODULI $OUTPUT $INPUT1 $VARMODULI1 $INPUT2 $VARMODULI2
