#!/bin/bash

MODULI="-moduli 16,16,16,16,16,16,16,16"
VARMODULI1="-varmoduli 16,8,8,8,8,16,8,8"
INPUT1="-input input/2/e6/{x^5+2x^3+2}/1.txt,input/2/e6/{x^5+2x^3+2}/2.txt,input/2/e6/{x^5+2x^3+2}/3.txt,input/2/e6/{x^5+2x^3+2}/4.txt,input/2/e6/{x^5+2x^3+2}/5.txt,input/2/e6/{x^5+2x^3+2}/6.txt,input/2/e6/{x^5+2x^3+2}/7.txt,input/2/e6/{x^5+2x^3+2}/8.txt"
OUTPUT="-output output2e6mod16.txt"
./build/apps/program $MODULI $OUTPUT $INPUT1 $VARMODULI1
