#!/bin/bash

MODULI="-moduli 5,5,5,5,5,5,5,5"
VARMODULI1="-varmoduli 5,5,5,1,5,1,1,1"
INPUT1="-input input/5/e4/{x+4x+4x^2+5x^4-10}/1.txt,input/5/e4/{x+4x+4x^2+5x^4-10}/2.txt,input/5/e4/{x+4x+4x^2+5x^4-10}/3.txt,input/5/e4/{x+4x+4x^2+5x^4-10}/4.txt,input/5/e4/{x+4x+4x^2+5x^4-10}/5.txt,input/5/e4/{x+4x+4x^2+5x^4-10}/6.txt,input/5/e4/{x+4x+4x^2+5x^4-10}/7.txt,input/5/e4/{x+4x+4x^2+5x^4-10}/8.txt"
VARMODULI2="-varmoduli 5,5,5,1,5,1,1,1"
INPUT2="-input input/5/e4/{x+4x+4x^2+5x^4+10}/1.txt,input/5/e4/{x+4x+4x^2+5x^4+10}/2.txt,input/5/e4/{x+4x+4x^2+5x^4+10}/3.txt,input/5/e4/{x+4x+4x^2+5x^4+10}/4.txt,input/5/e4/{x+4x+4x^2+5x^4+10}/5.txt,input/5/e4/{x+4x+4x^2+5x^4+10}/6.txt,input/5/e4/{x+4x+4x^2+5x^4+10}/7.txt,input/5/e4/{x+4x+4x^2+5x^4+10}/8.txt"
VARMODULI3="-varmoduli 5,5,5,1,5,1,1,1"
INPUT3="-input input/5/e4/{x+4x+4x^2+10x^4-5}/1.txt,input/5/e4/{x+4x+4x^2+10x^4-5}/2.txt,input/5/e4/{x+4x+4x^2+10x^4-5}/3.txt,input/5/e4/{x+4x+4x^2+10x^4-5}/4.txt,input/5/e4/{x+4x+4x^2+10x^4-5}/5.txt,input/5/e4/{x+4x+4x^2+10x^4-5}/6.txt,input/5/e4/{x+4x+4x^2+10x^4-5}/7.txt,input/5/e4/{x+4x+4x^2+10x^4-5}/8.txt"
VARMODULI4="-varmoduli 5,5,5,1,5,1,1,1"
INPUT4="-input input/5/e4/{x+4x+4x^2+10x^4+5}/1.txt,input/5/e4/{x+4x+4x^2+10x^4+5}/2.txt,input/5/e4/{x+4x+4x^2+10x^4+5}/3.txt,input/5/e4/{x+4x+4x^2+10x^4+5}/4.txt,input/5/e4/{x+4x+4x^2+10x^4+5}/5.txt,input/5/e4/{x+4x+4x^2+10x^4+5}/6.txt,input/5/e4/{x+4x+4x^2+10x^4+5}/7.txt,input/5/e4/{x+4x+4x^2+10x^4+5}/8.txt"
OUTPUT="-output output5e4mod5.txt"
./build/apps/program $MODULI $OUTPUT $INPUT1 $VARMODULI1 $INPUT2 $VARMODULI2 $INPUT3 $VARMODULI3 $INPUT4 $VARMODULI4
