#!/bin/bash

MODULI="-moduli 5,5,5,1,5,5,5,5"
VARMODULI1="-varmoduli 5,1,1,1,1,5,5,1"
INPUT1="-input input/5/e6/{x^5-5*x+5x+4x^2+10}/1.txt,input/5/e6/{x^5-5*x+5x+4x^2+10}/2.txt,input/5/e6/{x^5-5*x+5x+4x^2+10}/3.txt,input/5/e6/{x^5-5*x+5x+4x^2+10}/4.txt,input/5/e6/{x^5-5*x+5x+4x^2+10}/5.txt,input/5/e6/{x^5-5*x+5x+4x^2+10}/6.txt,input/5/e6/{x^5-5*x+5x+4x^2+10}/7.txt,input/5/e6/{x^5-5*x+5x+4x^2+10}/8.txt"
VARMODULI2="-varmoduli 5,1,5,1,1,1,1,1"
INPUT2="-input input/5/e6/{x^2+10x^6+5}/1.txt,input/5/e6/{x^2+10x^6+5}/2.txt,input/5/e6/{x^2+10x^6+5}/3.txt,input/5/e6/{x^2+10x^6+5}/4.txt,input/5/e6/{x^2+10x^6+5}/5.txt,input/5/e6/{x^2+10x^6+5}/6.txt,input/5/e6/{x^2+10x^6+5}/7.txt,input/5/e6/{x^2+10x^6+5}/8.txt"
VARMODULI3="-varmoduli 5,1,1,1,1,5,5,1"
INPUT3="-input input/5/e6/{x^5-10*x+5x+4x^2+5}/1.txt,input/5/e6/{x^5-10*x+5x+4x^2+5}/2.txt,input/5/e6/{x^5-10*x+5x+4x^2+5}/3.txt,input/5/e6/{x^5-10*x+5x+4x^2+5}/4.txt,input/5/e6/{x^5-10*x+5x+4x^2+5}/5.txt,input/5/e6/{x^5-10*x+5x+4x^2+5}/6.txt,input/5/e6/{x^5-10*x+5x+4x^2+5}/7.txt,input/5/e6/{x^5-10*x+5x+4x^2+5}/8.txt"
VARMODULI4="-varmoduli 5,1,1,1,1,1,5,1"
INPUT4="-input input/5/e6/{x^6+10x^2+5}/1.txt,input/5/e6/{x^6+10x^2+5}/2.txt,input/5/e6/{x^6+10x^2+5}/3.txt,input/5/e6/{x^6+10x^2+5}/4.txt,input/5/e6/{x^6+10x^2+5}/5.txt,input/5/e6/{x^6+10x^2+5}/6.txt,input/5/e6/{x^6+10x^2+5}/7.txt,input/5/e6/{x^6+10x^2+5}/8.txt"
VARMODULI5="-varmoduli 5,1,1,1,1,5,5,1"
INPUT5="-input input/5/e6/{x^5+10*x+5x+4x^2+5}/1.txt,input/5/e6/{x^5+10*x+5x+4x^2+5}/2.txt,input/5/e6/{x^5+10*x+5x+4x^2+5}/3.txt,input/5/e6/{x^5+10*x+5x+4x^2+5}/4.txt,input/5/e6/{x^5+10*x+5x+4x^2+5}/5.txt,input/5/e6/{x^5+10*x+5x+4x^2+5}/6.txt,input/5/e6/{x^5+10*x+5x+4x^2+5}/7.txt,input/5/e6/{x^5+10*x+5x+4x^2+5}/8.txt"
VARMODULI6="-varmoduli 5,1,1,1,1,5,5,1"
INPUT6="-input input/5/e6/{x^5+5*x+5x+4x^2+10}/1.txt,input/5/e6/{x^5+5*x+5x+4x^2+10}/2.txt,input/5/e6/{x^5+5*x+5x+4x^2+10}/3.txt,input/5/e6/{x^5+5*x+5x+4x^2+10}/4.txt,input/5/e6/{x^5+5*x+5x+4x^2+10}/5.txt,input/5/e6/{x^5+5*x+5x+4x^2+10}/6.txt,input/5/e6/{x^5+5*x+5x+4x^2+10}/7.txt,input/5/e6/{x^5+5*x+5x+4x^2+10}/8.txt"
VARMODULI7="-varmoduli 5,5,1,1,1,1,1,1"
INPUT7="-input input/5/e6/{x+4x^7+5}/1.txt,input/5/e6/{x+4x^7+5}/2.txt,input/5/e6/{x+4x^7+5}/3.txt,input/5/e6/{x+4x^7+5}/4.txt,input/5/e6/{x+4x^7+5}/5.txt,input/5/e6/{x+4x^7+5}/6.txt,input/5/e6/{x+4x^7+5}/7.txt,input/5/e6/{x+4x^7+5}/8.txt"
OUTPUT="-output output5e6mod5.txt"
./build/apps/program $MODULI $OUTPUT $INPUT1 $VARMODULI1 $INPUT2 $VARMODULI2 $INPUT3 $VARMODULI3 $INPUT4 $VARMODULI4 $INPUT5 $VARMODULI5 $INPUT6 $VARMODULI6 $INPUT7 $VARMODULI7
