#!/bin/bash

MODULI="-moduli 49,49,49,49,49,49,49,49"
VARMODULI1="-varmoduli 49,49,49,7,7,7,7,7"
INPUT1="-input input/7/e5/{x+6x+6x^6-21}/1.txt,input/7/e5/{x+6x+6x^6-21}/2.txt,input/7/e5/{x+6x+6x^6-21}/3.txt,input/7/e5/{x+6x+6x^6-21}/4.txt,input/7/e5/{x+6x+6x^6-21}/5.txt,input/7/e5/{x+6x+6x^6-21}/6.txt,input/7/e5/{x+6x+6x^6-21}/7.txt,input/7/e5/{x+6x+6x^6-21}/8.txt"
VARMODULI2="-varmoduli 49,7,7,7,7,7,49,49"
INPUT2="-input input/7/e5/{x^6+7x+6x+6}/1.txt,input/7/e5/{x^6+7x+6x+6}/2.txt,input/7/e5/{x^6+7x+6x+6}/3.txt,input/7/e5/{x^6+7x+6x+6}/4.txt,input/7/e5/{x^6+7x+6x+6}/5.txt,input/7/e5/{x^6+7x+6x+6}/6.txt,input/7/e5/{x^6+7x+6x+6}/7.txt,input/7/e5/{x^6+7x+6x+6}/8.txt"
VARMODULI3="-varmoduli 49,49,7,7,7,7,49,7"
INPUT3="-input input/7/e5/{x+6x^5+7x^2+21}/1.txt,input/7/e5/{x+6x^5+7x^2+21}/2.txt,input/7/e5/{x+6x^5+7x^2+21}/3.txt,input/7/e5/{x+6x^5+7x^2+21}/4.txt,input/7/e5/{x+6x^5+7x^2+21}/5.txt,input/7/e5/{x+6x^5+7x^2+21}/6.txt,input/7/e5/{x+6x^5+7x^2+21}/7.txt,input/7/e5/{x+6x^5+7x^2+21}/8.txt"
VARMODULI4="-varmoduli 49,49,49,7,7,7,7,7"
INPUT4="-input input/7/e5/{x+6x+6x^6+14}/1.txt,input/7/e5/{x+6x+6x^6+14}/2.txt,input/7/e5/{x+6x+6x^6+14}/3.txt,input/7/e5/{x+6x+6x^6+14}/4.txt,input/7/e5/{x+6x+6x^6+14}/5.txt,input/7/e5/{x+6x+6x^6+14}/6.txt,input/7/e5/{x+6x+6x^6+14}/7.txt,input/7/e5/{x+6x+6x^6+14}/8.txt"
OUTPUT="-output output7e5mod49.txt"
./build/apps/program $MODULI $OUTPUT $INPUT1 $VARMODULI1 $INPUT2 $VARMODULI2 $INPUT3 $VARMODULI3 $INPUT4 $VARMODULI4
