#!/bin/bash

DEGREE="-degree 8"
COEFFS="-coeffs 1"
DIVISORS="-divisors 1,1,1,1,1,1,1,1"
DISC="-discriminant -7"
MOD="-modulus 11"
TREE="-tree input/tree.txt"
OUTPUT="-output Mod11.txt"

./congr $DEGREE $COEFFS $DIVISORS $DISC $MOD $OUTPUT $TREE
